[package]
name = "pelt"
version = "0.1.0"
authors = ["ritchie46 <ritchie46@gmail.com>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Changepoint detection with Pruned Exact Linear Time"

[dependencies]
fnv = "1.0.3"

[lib]
name = "pelt"
